add CS100 Spring 2024
i-TechX/iTechX pull request #121
Opened 2024-07-15 14:12 UTC by TLNA114514

add lecture slides; add hw; add hw sol; add exam; add quiz

2024-07-16 00:44 UTC, why-in-Shanghaitech commented
Hi! Thank you very much for your contribution! I'll review this PR in a few days.

2024-07-21 05:02 UTC, why-in-Shanghaitech requested changes
The only issue is about people id. I can help you with this, but I am afraid I'll be very busy in the following month (till 18th, August).

2024-07-21 05:02 UTC, why-in-Shanghaitech commented on courses/CS100/meta.json
> +                "张敏慎",
Use chinese character or space may lead to undefined behaviour. These ids are also missing from the people database.

2024-07-21 05:05 UTC, why-in-Shanghaitech commented on courses/CS100/meta.json
> +                "张敏慎",
![image](https://github.com/user-attachments/assets/a54d6d6c-e36a-40fd-b23b-ff3394ad29ce)

Click here to create a new people in the database. The id is expected to be the email prefix (or something similar is okay). The name is what is displayed on the webpage.

2024-07-24 15:08 UTC, TLNA114514 commented
Alright, I've already finished it.However, I could not  know the exact name of the TA 'daihz'  , I decided to delete it in case that it may mislead others.

发自 Outlook<http://aka.ms/weboutlook>
________________________________
发件人: Haoyi Wu ***@***.***>
发送时间: 2024年7月21日 13:06
收件人: i-TechX/iTechX ***@***.***>
抄送: TLNA114514 ***@***.***>; Author ***@***.***>
主题: Re: [i-TechX/iTechX] add CS100 Spring 2024 (PR #121)


@why-in-Shanghaitech commented on this pull request.

________________________________

In courses/CS100/meta.json<https://github.com/i-TechX/iTechX/pull/121#discussion_r1685641377>:

> +                "李钟楷",
+                "Qingcheng Zhao",
+                "张涵锐",
+                "Zhiyu Yang",
+                "张中瀚",
+                "Yunlong Feng",
+                "daihzh",
+                "张敏慎",


image.png (view on web)<https://github.com/user-attachments/assets/a54d6d6c-e36a-40fd-b23b-ff3394ad29ce>

Click here to create a new people in the database. The id is expected to be the email prefix (or something similar is okay). The name is what is displayed on the webpage.

―
Reply to this email directly, view it on GitHub<https://github.com/i-TechX/iTechX/pull/121#discussion_r1685641377>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BCY2DD6RMDBO5575E322OHTZNM6UBAVCNFSM6AAAAABK4UOJSWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCOJQGIZDEMZUHA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-08-20 01:48 UTC, why-in-Shanghaitech approved these changes
LGTM, need to manually resolve the conflict
There is still one Chinese person id. I will fix it before merging.

2024-08-20 02:38 UTC, merged

2024-08-20 02:43 UTC, why-in-Shanghaitech commented
Again, thank you for your great contribution! These contents are now available at iTechX.

2024-08-21 04:15 UTC, TLNA114514 commented
Thank you very much！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Haoyi Wu ***@***.***>
发送时间: Tuesday, August 20, 2024 10:44:01 AM
收件人: i-TechX/iTechX ***@***.***>
抄送: TLNA114514 ***@***.***>; Author ***@***.***>
主题: Re: [i-TechX/iTechX] add CS100 Spring 2024 (PR #121)


Again, thank you for your great contribution! These contents are now available at iTechX.

―
Reply to this email directly, view it on GitHub<https://github.com/i-TechX/iTechX/pull/121#issuecomment-2297857933>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BCY2DDZJHRH4FED5DAYLCKDZSKUPDAVCNFSM6AAAAABK4UOJSWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJXHA2TOOJTGM>.
You are receiving this because you authored the thread.Message ID: ***@***.***>