File base
i-TechX/iTechX pull request #123
Opened 2024-10-16 07:32 UTC by guaiwu012

因文件过大，使用网盘分享

2024-10-16 12:14 UTC, why-in-Shanghaitech commented
Hi! Thank you very much for your contribution! I'll review this PR in a few days.
I've noticed that this is your first contribution. I'll add you to the contributor list once the pull request is accepted.

2024-10-24 01:47 UTC, why-in-Shanghaitech requested changes
There are several places that are possible to be improved. You may change directly in your personal space, or I could also make the changes for you later.

2024-10-24 01:47 UTC, why-in-Shanghaitech commented on courses/ARTS1422/ARTS1422.01_Spring_2024/Lecture Slides 教学课件/98e74de8425145ea9ca48d7a329cdc4.png
These files do not appear to exceed the 100M size limit. If possible, try not to use third-party tools to upload files.

2024-10-24 01:47 UTC, why-in-Shanghaitech commented on courses/ARTS1422/meta.json
> +            "ta": []
If there exists a TA, but you do not know who, please add "unknown". Leave this blank means there is no TA in this course.
```suggestion
            "ta": [
                "unknown"
            ]
```

2024-10-24 01:47 UTC, why-in-Shanghaitech commented on courses/CS173/meta.json
> +    "status": "activate",
A course is activated iff the instructor uses iTechX as the major platform and now is the course semester.
```suggestion
```

2024-10-24 01:47 UTC, why-in-Shanghaitech commented on courses/CS173/meta.json
> +                "unknown"
The TA is listed in the 1st slide.

2024-10-26 14:20 UTC, merged

2024-10-26 14:26 UTC, why-in-Shanghaitech commented
Again, thank you for your great contribution! These contents are now available at iTechX.
I have added you to the iTechX contributor list.

2024-10-28 05:00 UTC, guaiwu012 commented
I didn't check the message in time because I was busy before. Thank you for helping to upgrade the document I uploaded. In addition, itechx is a very good platform, thank you for everything you do for the students in shanghaitech!